version: "3"
services:
  frontend:
    restart: always
    resource_class: large
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: shjeon97/intranet-frontend:1.0.0
    container_name: intranet-frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3001:3000"

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: shjeon97/intranet-backend:1.0.0
    container_name: intranet-backend
    volumes:
      - /main/public/intranet/upload:/public/upload
    env_file:
      - ./backend/.env.production
    ports:
      - "4001:4000"
